config/routes.rb
Kidr::Application.routes.draw do
 
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  devise_for :users
  
  namespace :admin do
    resources :sites, :only => :index
    resources :users, :only => [:index, :edit, :update, :show, :destroy]
  end
  
  resources :sites, :except => [:show, :index] do
    member do
      get :edit_top_story
      put :update_top_story
    end
    resources :pages do
      resources :attachments
      resources :comments
      resources :archives
      resources :messages, :only => [:new, :create]
      member do
        put :reset
      end
      collection do
        post :reorder
      end
    end
    resources :events do
      collection { get :feed }
    end
      
    resources :documents do
      member do
        get :download
      end
    end
    resources :photos, :only => :index
    resources :messages, :only => [:index, :new, :create, :destroy]
    resources :memberships
    resources :invitations do
      member do 
        put :relay
      end
      collection do 
        get :new_many
        post :create_many
      end
    end
    resources :log_entries, :only => :index
  end
  resources :feedbacks
  resources :events, :only => :index do
    collection { get :feed }
  end
  
  root :to => 'application#show'
  match "/about", :to => 'application#about', :as => :about
  match "/tour", :to => 'application#tour', :as => :tour
  match "/advisors", :to => 'application#advisors', :as => :advisors
  match "/privacy", :to => 'application#privacy', :as => :privacy
  match "/terms", :to => 'application#terms', :as => :terms
  
  # Finally - show a page...
  
  match "/:site_permalink" => "sites#show", :as => :site_root
  match "/:site_permalink(/:page_permalink)" => "pages#show", :as => :permalink

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :site
  belongs_to :user # Author, usually.  Nil means site

  belongs_to :page
  belongs_to :comment
  belongs_to :event

  has_many :notifications

  validates_presence_of :body

  before_create :set_subject
  after_create :create_instant_notifications

  def create_instant_notifications
    for user in self.site.users
      self.notifications.create(:email => user.email)
    end
    for invite in self.site.invitations
      self.notifications.create(:email => invite.email)
    end
  end

  def set_subject
    self.subject = "#{self.site.name}"
    if self.page
      self.subject += ": #{self.page.name}"
    end
    if self.comment
      self.subject += " comment from #{self.comment.user.try(:name)}"
    end
    if self.event
      self.subject += " reminder: #{self.event.name}"
    end
    if self.user
      self.subject += ": a message from #{self.user.name}"
    end
  end
  
    
  def stop_double_click
    errors.add_to_base('The message was created') if Message.find(:first, :conditions => ['body = ? AND user_id = ? AND created_at > ?', self.body, self.user_id, 1.minute.ago])
  end
  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  
  before_filter :authenticate_user!
  before_filter :site_editor_required!
  
  def index
    @messages = @site.messages.order("created_at desc").all.paginate(:page => params[:page], :per_page => 10)
  end
  
  def new
    @message = @site.messages.build(params[:message])
    if params[:page_id]  
      @page = @site.pages.find(params[:page_id])
      @message.page = @page
    end
  end
  
  def create
    @message = @site.messages.build(params[:message])
    @message.user = current_user
    if params[:page_id]  
      @page = @site.pages.find(params[:page_id])
      @message.page = @page
    end
    if @message.save
      flash[:notice] = 'Message was created successfully'
      respond_to do |format| 
        format.html { redirect_to site_messages_path(@site) }
        format.js { 
          render :update do |page|
            page.replace_html 'messages', :partial => "messages/messages", :locals => { :site => @site,  :page => @page, :messages => @page ? @page.messages : @site.messages }
          end  
        }
      end
    else
      render :action => :new
    end
  end
  
  
  def destroy
    @page = @site.pages.not_deleted.find(params[:page_id])
    @message = @page.messages.find(params[:id])
    @message.destroy if (current_user.can_edit?(@site) || @message.user.eql?(current_user))
    LogEntry.create!(:loggable => @comment, :site => @site, :user => current_user, :description => 'comment_delete')
    render :update do |page|
      page.replace_html 'comments', :partial => "comments/page_comments", :locals => { :page => @comment.page }
    end
  end
  
end

app/views/messages/_message.html.haml
%div.message[message]
  - if message.user
    .image.small
      = image_tag message.user.avatar.url(:small)
  - if message.page || message.event
    .action{:style => 'float:right; margin-left: 1em'}
      - if message.page
        = link_to message.page.name, permalink_path(message.page.site.permalink, message.page.permalink)
      - if message.event
        #{link_to_function message.event.name, "Modalbox.show('#{site_event_path(message.event.site, message.event)}', {title: '#{message.event.name}', width: 460, overlayDuration:0.1, slideDownDuration:0.1}); return false;"} 
  .details
    %b= message.user ? message.user.display_name : 'System'
    %span.date= message.created_at.to_s(:date)
    .description
      = raw message.body
  

app/views/messages/_messages.html.haml
- if @site
  - if current_user
    = link_to_function "Add message", "$('new_message').show();$(this).hide();"
    - form_for [@site, page, Message.new(:user_id => current_user.id, :page => page, :site => @site)], :remote => true, :html => {:style => 'display:none'} do |f|
      %ul.form
        = f.hidden_field 'page_id'
        %li
          %span.hint
            Logged in as #{current_user.display_name}
          %br/
          = f.text_area 'body'
        %li= submit_tag 'Add Message', :id => "add_message_button"
  - else
    %p.hint
      = link_to 'Sign in', new_user_session_path
      to leave a message

= render :partial => 'messages/message', :collection => messages

app/views/messages/index.html.haml
- @page_title = 'Messages'
- @breadcrumbs << @page_title
- @page_actions = link_to("Create Message", new_site_message_path(@site))
%ul.comments
  = render @messages
= will_paginate(@messages)

app/views/messages/new.html.haml
- @page_title = "Send a message"
- @breadcrumbs << link_to('Messages', site_messages_path(@site)) << @page_title
= raw error_messages_for @message
%p
  %b Members:
  = @site.users.map{|u| u.name }.join(', ')
- if @site.invitations.any?
  %p
    %b Invited: 
    = @site.invitations.map{|i| i.name }.join(', ')
  
- simple_form_for [@site, @page, @message] do |f|
  .inputs
    = f.input :body, :label => 'Your message', :label_html => { :style => 'display:block' }, :input_html => { :style => 'width:600px', :rows => '4' }
    .input
      #{f.label :page_id, 'References page', :style => 'width:auto'}#{f.select :page_id, @site.pages.map{|p| [p.name, p.id]}, :include_blank => true}
      = f.check_box :embed_page
      = f.label :embed_page, 'Embed page content in email'
  .actions
    = submit_tag 'Send message'
    
#page_content


= javascript_tag js_md = "if( $('message_embed_page').checked && $('message_page_id').getValue() > 0 ) { new Ajax.Request( '#{site_pages_path(@site)}/' + $('message_page_id').getValue() + '.js', { method: 'get', onComplete: function(transport) { $('page_content').innerHTML = transport.responseText } } )  } else { $('page_content').innerHTML = '' }"
= observe_field :message_embed_page, :function => js_md
= observe_field :message_page_id, :function => js_md