config/routes.rb
Kidr::Application.routes.draw do
 
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  devise_for :users
  
  namespace :admin do
    resources :sites, :only => :index
    resources :users, :only => [:index, :edit, :update, :show, :destroy]
  end
  
  resources :sites, :except => [:show, :index] do
    member do
      get :edit_top_story
      put :update_top_story
    end
    resources :pages do
      resources :attachments
      resources :comments
      resources :archives
      resources :messages, :only => [:new, :create]
      member do
        put :reset
      end
      collection do
        post :reorder
      end
    end
    resources :events do
      collection { get :feed }
    end
      
    resources :documents do
      member do
        get :download
      end
    end
    resources :photos, :only => :index
    resources :messages, :only => [:index, :new, :create, :destroy]
    resources :memberships
    resources :invitations do
      member do 
        put :relay
      end
      collection do 
        get :new_many
        post :create_many
      end
    end
    resources :log_entries, :only => :index
  end
  resources :feedbacks
  resources :events, :only => :index do
    collection { get :feed }
  end
  
  root :to => 'application#show'
  match "/about", :to => 'application#about', :as => :about
  match "/tour", :to => 'application#tour', :as => :tour
  match "/advisors", :to => 'application#advisors', :as => :advisors
  match "/privacy", :to => 'application#privacy', :as => :privacy
  match "/terms", :to => 'application#terms', :as => :terms
  
  # Finally - show a page...
  
  match "/:site_permalink" => "sites#show", :as => :site_root
  match "/:site_permalink(/:page_permalink)" => "pages#show", :as => :permalink

end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :site
  belongs_to :user
  belongs_to :role
  
  attr_accessor :email, :passcode
  
  before_validation :set_user, :on => :create
  
  validates_presence_of :user
  validates_format_of :email, :with => /^[a-zA-Z0-9.\+_%-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/, :if => :email
  
  validates_uniqueness_of :user_id, :scope => :site_id, :message => 'is already a member'
  
  validate :confirm_passcode, :on => :create
  
  after_create :delete_invitation
  
  def set_user
    if self.email.present? && self.user.nil?
      user = User.find_by_email(self.email) || User.create(:email => self.email, :password => (rand(1000000) + 1000000).to_s)
      self.user_id = user.id
    end
  end
  
  def can_edit?
    return self.role.name == 'editor' || self.role.name == 'admin' 
  end
  
  def can_administrate?
    return self.role.name == 'admin' 
  end
  
  def confirm_passcode
    self.errors.add_to_base 'Wrong passcode' unless self.site.nil? || self.passcode == self.site.passcode
  end
  
  def delete_invitation
    self.site.invitations.where("email = '#{self.user.email}'").each { |i| i.destroy }
  end

end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  
  before_filter :authenticate_user!
  before_filter :site_admin_required!, :except => [:new, :create]
  skip_before_filter :ensure_membership, :only => [:new, :create]
  
  def index
    @memberships = @site.memberships.includes(:user).order('memberships.role_id desc, users.name asc, users.email asc')
  end

  def new
    @membership = @site.memberships.build
  end

  def create
    @membership = @site.memberships.build(params[:membership])
    @membership.role ||= Role.member
    @membership.user = current_user unless @membership.email.present?
    if @membership.save
      flash[:notice] = 'The member was successfully added.'
      if @membership.user == current_user
        redirect_to site_root_path(@site.permalink)
      else
        redirect_to new_site_membership_path(@site)
      end
    else
      render :action => :new
    end
  end
  
  def edit
    @page_title = "Edit members"
    @membership = @site.memberships.find(params[:id])
  end
  
  def update
    @membership = @site.memberships.find(params[:id])  
    if @membership.update_attributes(params[:membership])
    flash[:notice] = 'The member was successfully updated.'
      redirect_to site_memberships_path(@site)
    else
      render :action => :edit
    end
  end

  def destroy
    @membership = @site.memberships.find(params[:id]) 
    @membership.destroy
    flash[:notice] = 'User \'' + @membership.user.display_name + '\' was successfully removed.'
    redirect_to site_memberships_path(@site)
  end
  
end

app/views/memberships/_membership.html.haml
%tr
  %td
    %strong #{membership.user.display_name} 
    %br
    #{membership.user.email}
    - if membership.user.phone.present?
      %br
      = membership.user.phone 
  %td
    = membership.role.name
  %td
    = link_to 'Edit', edit_site_membership_path(membership.site, membership)
    = link_to 'Remove', site_membership_path(membership.site, membership), :method => :delete, :confirm => 'Are you sure you want to remove this user?'

app/views/memberships/edit.html.haml
- @page_title = 'Edit Membership'
- @breadcrumbs << link_to('Memberships', site_memberships_path(@site)) << @page_title

- form_for [@site, @membership] do |f|
  = raw error_messages_for @membership
  = hidden_field_tag 'site_id', @site.id
  %ul.form
    %li
      = f.label :name
      = @membership.user.name
    %li
      = f.label :email
      = @membership.user.email
    %li
      = f.label :role_id
      = f.select :role_id, Role.all.map{|role| [role.name, role.id]}
    %li.indent
      = f.submit 'Save Changes'

app/views/memberships/index.html.haml
- @page_title = 'Memberships'
- @breadcrumbs << @page_title
- @page_actions = capture do 
  = link_to("Invite one", new_site_invitation_path(@site))
  = link_to("Invite many", new_many_site_invitations_path(@site))

%p
  = link_to_unless_current('Members', site_memberships_path(@site))
  |
  = link_to_unless_current('Open Invitations', site_invitations_path(@site))
%table.grid
  %thead
    %tr
      %th User
      %th Role
      %th Actions
  %tbody
    = render @memberships

app/views/memberships/new.html.haml
- @page_title = 'New Member'
- @breadcrumbs << link_to('Memberships', site_memberships_path(@site)) << @page_title

- if @site.members_only?
  %p
    This is a private group.  Only members are allowed.
    
%p
  To join this group, please enter your email address and the site's passcode.  You can get the passcode from the site administrator.
  
  
- form_for [@site, @membership] do |f|
  = raw error_messages_for @membership
  = hidden_field_tag 'site_id', @site.id
  %ul.form
    %li
      = f.label :passcode
      = f.text_field :passcode
    %li.indent
      = f.submit "Create Membership"