config/routes.rb
Kidr::Application.routes.draw do
 
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  devise_for :users
  
  namespace :admin do
    resources :sites, :only => :index
    resources :users, :only => [:index, :edit, :update, :show, :destroy]
  end
  
  resources :sites, :except => [:show, :index] do
    member do
      get :edit_top_story
      put :update_top_story
    end
    resources :pages do
      resources :attachments
      resources :comments
      resources :archives
      resources :messages, :only => [:new, :create]
      member do
        put :reset
      end
      collection do
        post :reorder
      end
    end
    resources :events do
      collection { get :feed }
    end
      
    resources :documents do
      member do
        get :download
      end
    end
    resources :photos, :only => :index
    resources :messages, :only => [:index, :new, :create, :destroy]
    resources :memberships
    resources :invitations do
      member do 
        put :relay
      end
      collection do 
        get :new_many
        post :create_many
      end
    end
    resources :log_entries, :only => :index
  end
  resources :feedbacks
  resources :events, :only => :index do
    collection { get :feed }
  end
  
  root :to => 'application#show'
  match "/about", :to => 'application#about', :as => :about
  match "/tour", :to => 'application#tour', :as => :tour
  match "/advisors", :to => 'application#advisors', :as => :advisors
  match "/privacy", :to => 'application#privacy', :as => :privacy
  match "/terms", :to => 'application#terms', :as => :terms
  
  # Finally - show a page...
  
  match "/:site_permalink" => "sites#show", :as => :site_root
  match "/:site_permalink(/:page_permalink)" => "pages#show", :as => :permalink

end

app/models/event.rb
class Event < ActiveRecord::Base
  
  has_event_calendar :start_at_field  => 'start_on', :end_at_field => 'end_on'
  
  belongs_to :site
  belongs_to :page
  has_many :log_entries, :as => :loggable
  has_many :messages
  
  validates_presence_of :name

  before_save :set_end_on, :set_time, :set_remind_on
  
  attr_accessor :reminder
  # :multi_day was removed
  
  scope :remind_today, lambda { where('Date(remind_on) = ?', Date.today)}
  scope :think_about, lambda { where('Date(start_on) > ?', 1.weeks.ago).order(:start_on).limit(6)}
  scope :coming_up, lambda { where('Date(start_on) between ? AND ?', Date.today, 6.weeks.from_now).order('start_on') }
  scope :for_user, lambda { |user| where('memberships.user_id = ?', user.id).includes(:site => :memberships) }

  def set_end_on 
    self.end_on = self.start_on if self.end_on.blank?
    self.end_on = self.start_on if self.end_on < self.start_on
    self.end_time = self.start_time + 30.minutes if (self.end_on == self.start_on && (self.end_time.blank? || self.end_time < self.start_time))
  end
  
  def set_time
    if self.all_day?
      self.start_on = self.start_on.strftime("%Y%m%d") + 'T000000'
      self.end_on = self.end_on.strftime("%Y%m%d") + 'T000000'
      self.start_time = self.end_time = nil
    else
      self.start_on = self.start_on.strftime("%Y%m%d") + 'T' + self.start_time.strftime("%H%M%S")
      self.end_on = self.end_on.strftime("%Y%m%d") + 'T' + self.end_time.strftime("%H%M%S")
    end
  end
  
  def set_remind_on
    self.remind_on = nil if self.reminder == '0'
  end
  
  def self.send_reminders
    for event in Event.remind_today
      event.site.messages.create(:event => event, :page => event.page, :body => "#{event.name} #{event.description}") unless event.messages.where('Date(created_at) = ?', Date.today).any?
    end
  end
  
  def assign_to_ical_event(ical_event, options = {})
    if options[:site]
      ical_event.summary = "#{self.name}"
    else
      ical_event.summary = "#{self.site.name}: #{self.name}"
    end
    ical_event.description = self.description.to_s
    if self.all_day? || self.start_time.blank?
      ical_event.dtstart =  self.start_on.gmtime.strftime("%Y%m%d")
    else
      ical_event.dtstart =  self.start_on.gmtime.strftime("%Y%m%dT%H%M%SZ")
    end
    if self.start_on < self.end_on
      ical_event.dtend = self.end_on.gmtime.strftime("%Y%m%d") 
      if self.all_day? || self.end_time.blank?
        ical_event.dtend =  (self.end_on + 1.day).gmtime.strftime("%Y%m%d")
      else
        ical_event.dtend =  self.end_on.gmtime.strftime("%Y%m%dT%H%M%SZ")
      end
    end 
    ical_event.location = self.location.to_s
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_filter :authenticate_user!, :except => :feed
  before_filter :authenticate_user!, :if => :site_members_only
  before_filter :site_editor_required!, :except => [:index, :show, :feed]
  
  before_filter :site_member_required!, :only => [:index, :show]
  before_filter :site_member_required!, :only => [:index, :show, :feed], :if => :site_members_only

  def index
    @month = (params[:month] || Time.zone.now.month).to_i
    @year = (params[:year] || Time.zone.now.year).to_i
    @shown_month = Date.civil(@year, @month)
    @event_strips = @site.events.event_strips_for_month(@shown_month)
  end
  
  def feed
    respond_to do |format| 
      format.ics { render :text => (@site ? @site.ical.export : current_user.ical.export) }
    end
  end
  
  def show
    @event = @site.events.find(params[:id])
    render :layout => false
  end

  def new
    if params[:year] && params[:month] && params[:day]
      @start_on = Time.parse("#{params[:year]}-#{params[:month]}-#{params[:day]}").to_datetime
      @end_on = Time.parse("#{params[:year]}-#{params[:month]}-#{params[:day]}").to_datetime
      @start_time = Time.parse('12:00')
      @end_time = Time.parse('13:00')
      @remind_on = @start_on - 2.days
    end
    @event = @site.events.build(:start_on => @start_on, :end_on => @end_on, :start_time => @start_time, :end_time => @end_time, :remind_on => @remind_on, :reminder => false)
  end
  
  def create
    @event = @site.events.build(params[:event])
    if @event.save
      redirect_to site_events_path(:month => @event.start_on.month)
      return false
    else
      render :action => :new
    end
  end


  def edit
    @event = @site.events.find(params[:id])
    @event.reminder = @event.remind_on.present?
    @event.remind_on = @event.start_on - 2.days unless @event.remind_on
  end

  def update
    @event = @site.events.find(params[:id])
    if @event.update_attributes(params[:event])
      flash[:notice] = "Event was updated successfully"
      redirect_to site_events_path(:month => @event.start_on.month)
      return false
    else
      render :action => :edit
    end
  end
  
  def destroy
    @event = @site.events.find(params[:id])
    @event.destroy if @event
    redirect_to site_events_path(:month => @event.start_on.month)
  end
  
end

app/views/events/_form.html.haml
= raw error_messages_for @event
- form_for [@site, @event] do |f|
  %ul.form{:style => 'margin-bottom:0'}
    - if  @event && !@event.new_record?
      %li{:style => "float:right"}= link_to "Delete event", site_event_path(@site,  @event), :confirm => "Are you sure you want to delete this event?", :method => :delete
    %li
      = f.label :name
      = f.text_field :name, :style => 'width:150px'
      = f.label :page_id, 'References page', :style => 'width:150px'
      = f.select :page_id, @site.pages.not_deleted.map{|p| [p.name, p.id]}, :include_blank => true
    %li
      = f.label :location
      = f.text_field :location, :style => 'width:400px'
    %li.indent
      = f.check_box :all_day
      = f.label :all_day, 'All day', :style => 'width:auto'
    %li#start_at_fields
      = f.label :start_on, 'Start date'
      = f.calendar_date_select :start_on, :time => false, :style => 'width:100px'
      %span#start_at_time
        = f.label :start_time
        = f.time_select :start_time, {:minute_step => 5}
      
    %li#end_at_fields
      = f.label :end_on, 'End date'
      = f.calendar_date_select :end_on, :time => false, :style => 'width:100px'
      %span#end_at_time
        = f.label :end_time
        = f.time_select :end_time, {:minute_step => 5}
    %li
      = f.label :description
      = f.text_area :description, :style => 'width:400px; height:70px'
    %li.indent
      = f.check_box :reminder
      = f.label :reminder, 'Send a reminder', :style => 'width:auto'
    %li#remind_on_field
      = f.label :remind_on, "On this day"
      = f.calendar_date_select :remind_on, :time => false, :style => 'width:100px'
    %li.indent
      = f.submit button_value
= javascript_tag js_r = "if($('event_reminder').checked){$('remind_on_field').show()} else {$('remind_on_field').hide()}"
= observe_field :event_reminder, :function => js_r
= javascript_tag js_time = "if($('event_all_day').checked){ $('start_at_time').hide();$('end_at_time').hide(); }else{$('start_at_time').show();$('end_at_time').show();}"
= observe_field :event_all_day, :function => js_time
= javascript_tag "$$('#event_start_time_4i option').each(function(option) { option.update(convert_hour(option.innerHTML)) })"
= javascript_tag "$$('#event_end_time_4i option').each(function(option) { option.update(convert_hour(option.innerHTML)) })"
  

app/views/events/_upcoming_events.html.haml
%ul.events
  - month = ''
  - for event in upcoming_events
    - if month != event.start_on.to_s(:month)
      %li.month
        = month = event.start_on.to_s(:month)
    %li.event
      .date
        - if (event.end_on.beginning_of_day > event.start_on.beginning_of_day)
          .wday
            %span.small
              #{event.start_on.to_s(:wday)}-#{event.end_on.to_s(:wday)}
          .dom.small
            %span.small
              = "#{event.start_on.to_s(:dom).strip}-#{event.end_on.to_s(:dom).strip}"
        - else
          .wday
            #{event.start_on.to_s(:wday)}
          .dom
            #{event.start_on.to_s(:dom)}
      .info
        .name 
          #{link_to_function event.name, "Modalbox.show('#{site_event_path(event.site, event)}', {title: '#{event.name}', width: 460, overlayDuration:0.1, slideDownDuration:0.1}); return false;"}         
          - if @site.nil?
            \- #{link_to(event.site.name, permalink_path(event.site.permalink))}
        .description
          - unless event.all_day?
            #{event.start_on.to_s(:time)}#{"-#{event.end_on.to_s(:time).strip}" if event.start_on.beginning_of_day == event.end_on.beginning_of_day}
          - if event.location.present?
            at #{event.location}
          #{event.description.truncate(140)}

app/views/events/edit.html.haml
- @page_title = 'Edit event'
- @breadcrumbs << link_to('Events', site_events_path(@site)) << @page_title
= render 'form', :button_value => 'Save Changes'

app/views/events/index.html.haml
- @page_title = 'Events'
- @breadcrumbs << @page_title
- @page_actions = link_to("Create Event", new_site_event_path(@site))
= raw event_calendar

app/views/events/new.html.haml
- @page_title = 'New Event'
- @breadcrumbs << link_to('Events', site_events_path(@site)) << @page_title
= render 'form', :button_value => 'Create Event'

app/views/events/show.html.haml
- if current_user.can_edit?(@site)

.events
  .event
  
    %div{:style => 'float:right'}
      = link_to 'Edit', edit_site_event_path(@site, @event)
    .date
      .wday
        #{@event.start_on.to_s(:wday)}
      .dom
        #{@event.start_on.to_s(:dom)}
    .info
      - if @event.location
        %b Location:
        = @event.location
        %br
      %b Date#{" and Time" unless !@event.all_day? }:
      = @event.start_on.to_s(:date)  
      - if !@event.all_day?
        = @event.start_on.try(:to_s, :time)
      - if @event.start_on < @event.end_on
        to #{@event.end_on.to_s(:date)}
      - if !@event.all_day?
        = @event.end_on.try(:to_s, :time)

      - if @event.remind_on
        %br
        %b Reminder: 
        = @event.remind_on.to_s(:date)
    
      - if @event.page && @event.page != @page
        %br
        %b Page: 
        = link_to @event.page.name, permalink_path(@site.permalink, @event.page.permalink)

      - if @event.description.present?
        %p
          = @event.description    