config/routes.rb
Kidr::Application.routes.draw do
 
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  devise_for :users
  
  namespace :admin do
    resources :sites, :only => :index
    resources :users, :only => [:index, :edit, :update, :show, :destroy]
  end
  
  resources :sites, :except => [:show, :index] do
    member do
      get :edit_top_story
      put :update_top_story
    end
    resources :pages do
      resources :attachments
      resources :comments
      resources :archives
      resources :messages, :only => [:new, :create]
      member do
        put :reset
      end
      collection do
        post :reorder
      end
    end
    resources :events do
      collection { get :feed }
    end
      
    resources :documents do
      member do
        get :download
      end
    end
    resources :photos, :only => :index
    resources :messages, :only => [:index, :new, :create, :destroy]
    resources :memberships
    resources :invitations do
      member do 
        put :relay
      end
      collection do 
        get :new_many
        post :create_many
      end
    end
    resources :log_entries, :only => :index
  end
  resources :feedbacks
  resources :events, :only => :index do
    collection { get :feed }
  end
  
  root :to => 'application#show'
  match "/about", :to => 'application#about', :as => :about
  match "/tour", :to => 'application#tour', :as => :tour
  match "/advisors", :to => 'application#advisors', :as => :advisors
  match "/privacy", :to => 'application#privacy', :as => :privacy
  match "/terms", :to => 'application#terms', :as => :terms
  
  # Finally - show a page...
  
  match "/:site_permalink" => "sites#show", :as => :site_root
  match "/:site_permalink(/:page_permalink)" => "pages#show", :as => :permalink

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  
  belongs_to :site
  
  validates_format_of :email, :with => /^[a-zA-Z0-9.\+_%-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/, :if => :email
  
  validates_uniqueness_of :email, :scope => :site_id
  
  validate :not_a_member
  
  after_create :create_member_if_user
  
  def not_a_member
    self.errors.add_to_base("This email is already a member") if self.site.users.find_by_email(self.email).present?
  end
  
  def create_member_if_user
    if user = User.find_by_email(self.email)
      self.site.memberships.create(:user => user, :passcode => self.site.passcode, :role => Role.member)
    end
  end
  
  def name
    self.email.split('@').first
  end
  
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  
  before_filter :authenticate_user!
  before_filter :site_admin_required!
  
  def index
    @invitations = @site.invitations.all
  end
  
  def relay
    @invitation = @site.invitations.find(params[:id])
    
    Mailer::invite(@invitation).deliver
    render :update do |page|
      page.replace "relay_#{dom_id(@invitation)}", :text => "<span style='color:red'>Invite sent!</span>"
    end
  end

  def new
    @invitation = @site.invitations.build
  end

  def create
    @invitation = @site.invitations.build(params[:invitation])
    if user = User.find_by_email(@invitation.email)
      if @site.users.include?(user) 
        flash[:notice] = "This user is already a member"
        render :action => :new
        return false
      elsif membership = @site.memberships.create(:user => user, :site => @invitation.site, :role => Role.member, :passcode => @invitation.site.passcode)        
        Mailer::confirm_membership(membership).deliver
        flash[:notice] = "The membership was created and a notice was sent"
        redirect_to site_memberships_path(@site)
      else  
        flash[:notice] = "The membership could not be created"
        redirect_to site_memberships_path(@site)
      end
    elsif @invitation.save
      Mailer::invite(@invitation).deliver
      flash[:notice] = "The invitation was sent"
      redirect_to site_invitations_path(@site)
    else
      render :action => :new
      return false
    end
  end
  
  def new_many
    # nothing to do here.
  end
  
  def create_many
    potential_emails = params[:invitation_emails].split(/[<>\s,'"]+/)
    potential_emails = potential_emails.select{|e| e =~ User::EMAIL_REGEX }    
    invitations_added_count = 0
    members_created_count = 0
    members_found_count = 0
    errors_count = 0
    for potential_email in potential_emails
      invitation = @site.invitations.build(:email => potential_email)  
      
      if user = User.find_by_email(invitation.email)
        if @site.users.include?(user) 
          members_found_count += 1
        elsif membership = @site.memberships.create(:user => user, :site => invitation.site, :role => Role.member, :passcode => invitation.site.passcode)        
          members_created_count += 1
          Mailer::confirm_membership(membership).deliver
        else  
          errors_count += 1
        end
      elsif invitation.save
        invitations_added_count += 1
        Mailer::invite(invitation).deliver
      end
      
    end
    flash[:notice] = "#{invitations_added_count} new invitation#{invitations_added_count != 1 ? 's were' : ' was'  } sent."
    flash[:notice] += " #{members_created_count} new member#{members_created_count != 1 ? 's were' : ' was'  } created." if members_created_count > 0
    flash[:notice] += " #{members_found_count} existing member#{members_found_count != 1 ? 's were' : ' was'  } found." if members_found_count > 0
    flash[:notice] += " #{errors_count} invitation#{members_found_count != 1 ? 's were' : ' was'  } not processed due to an error." if errors_count > 0
    
    redirect_to site_invitations_path(@site)
  end
  
  def destroy
    @invitation = @site.invitations.find(params[:id]) 
    @invitation.destroy
    flash[:notice] = 'The invitation was deleted.'
    redirect_to site_invitations_path(@site)
  end
end

app/views/invitations/_form.html.haml
- form_for [@site, @invitation] do |f|
  = raw error_messages_for @invitation
  = hidden_field_tag 'site_id', @site.id
  %ul.form
    %li
      = f.label :email
      = f.text_field :email
    %li.indent
      = f.submit button_value

app/views/invitations/_invitation.html.haml
%tr
  %td
    = invitation.email
  %td
    = link_to 'Remove', site_invitation_path(invitation.site, invitation), :method => :delete, :confirm => 'Are you sure you want to delete this invitation?'
    %span{:id => "relay_#{dom_id(invitation)}"}= link_to 'Send again', relay_site_invitation_path(invitation.site, invitation), :remote => true, :method => :put
  %td
    = invitation.created_at.to_s(:date)

app/views/invitations/index.html.haml
- @page_title = 'Invitations'
- @breadcrumbs << @page_title
- @page_actions = capture do 
  = link_to("Invite one", new_site_invitation_path(@site))
  = link_to("Invite many", new_many_site_invitations_path(@site))
%p
  When invitations are sent, the recipient will be given the site passcode, which is '#{@site.passcode}'

%p  
  = link_to_unless_current('Members', site_memberships_path(@site))
  |
  = link_to_unless_current('Open Invitations', site_invitations_path(@site))
%table.grid
  %thead
    %tr
      %th User
      %th Actions
      %th First Sent
  %tbody
    = render @invitations

app/views/invitations/new.html.haml
- @page_title = 'Send Invitation'
- @breadcrumbs << link_to('Invitations', site_invitations_path(@site)) << @page_title
= render 'form', :button_value => 'Send Invitation'

app/views/invitations/new_many.html.haml
- @page_title = "Create invitations"
- @breadcrumbs << link_to('Invitations', site_invitations_path(@site)) << @page_title
- form_tag create_many_site_invitations_path do
  = raw error_messages_for @site
  %ul.form
    %li
      = label_tag :invitation_emails, nil, :style => 'width:auto'
      %br
        = text_area_tag :invitation_emails, nil, :style => 'width:50%; height:150px'
    %li
      = submit_tag 'Create Invitations'